version: '3'
services:
        bitcoin-server-main:
                build:
                        context: ./bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server-main
                networks:
                        - bitcoin_local_net_main
                volumes:
                        - /mnt/ssd/bitcoin:/bitcoin
                command: [ "bitcoind" ]

        bitcoin-server-test:
                build:
                        context: ./bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server-test
                networks:
                        - bitcoin_local_net_test
                volumes:
                        - /mnt/ssd/bitcoin-test:/bitcoin
                command: [ "bitcoind", "-testnet" ]

        bitcoin-access-main:
                build:
                        context: ./bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access-main
                depends_on:
                        - bitcoin-server-main
                environment:
                        - RPC_HOST=bitcoin-server-main
                        - RPC_PORT=8332
                networks:
                        - bitcoin_local_net_main
                volumes:
                        - ./bitcoin-access/src:/mnt

        bitcoin-access-test:
                build:
                        context: ./bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access-test
                depends_on:
                        - bitcoin-server-test
                environment:
                        - RPC_HOST=bitcoin-server-test
                        - RPC_PORT=18332
                networks:
                        - bitcoin_local_net_test
                volumes:
                        - ./bitcoin-access/src:/mnt

        analytics:
                build:
                        context: ./analytics
                image: frt/blockchain-analytics
                tty: true
                container_name: blockchain-analytics
                environment:
                        - RPC_MAIN_HOST=bitcoin-access-main
                        - RPC_MAIN_PORT=8332
                        - RPC_TEST_HOST=bitcoin-access-test
                        - RPC_TEST_PORT=18332
                volumes:
                        - ./analytics/src:/mnt
                        - ./dbs:/db
                ports:
                        - 127.0.0.1:12346:8888
                networks:
                        - bitcoin_local_net_main
                        - bitcoin_local_net_test

networks:
        bitcoin_local_net_main: 
        bitcoin_local_net_test:
        eth_local_net_main:


