version: '3'
services:
        bitcoin-server:
                build:
                        context: .
                        dockerfile: Dockerfile-bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server
                networks:
                        bitcoin_local_net:
                                ipv4_address: 192.168.1.2
                volumes:
                        - /mnt/ssd/bitcoin:/bitcoin
                command: ["bitcoind"]
        bitcoin-server-test:
                build:
                        context: .
                        dockerfile: Dockerfile-bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server-test
                networks:
                        bitcoin_local_net_test:
                                ipv4_address: 192.168.2.2
                volumes:
                        - /mnt/ssd/bitcoin-test:/bitcoin
                command: ["bitcoind", "-testnet"]
        bitcoin-access:
                build:
                        context: .
                        dockerfile: Dockerfile-bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access
                depends_on:
                        - bitcoin-server
                environment:
                        - RPC_PORT=8332
                        - RPC_HOST=192.168.1.2
                networks:
                        bitcoin_local_net:
                                ipv4_address: 192.168.1.3
                volumes:
                        - ./src:/mnt
                        - /mnt/ssd/bitcoin-dbs:/db
        bitcoin-access-test:
                build:
                        context: .
                        dockerfile: Dockerfile-bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access-test
                depends_on:
                        - bitcoin-server-test
                environment:
                        - RPC_PORT=18332
                        - RPC_HOST=192.168.2.2
                networks:
                        bitcoin_local_net_test:
                                ipv4_address: 192.168.2.3
                volumes:
                        - ./src:/mnt
                        - /mnt/ssd/bitcoin-dbs:/db

networks:
        bitcoin_local_net:
                ipam:
                        config:
                                - subnet: 192.168.1.0/24
        bitcoin_local_net_test:
                ipam:
                        config:
                                - subnet: 192.168.2.0/24
