version: '3'
services:
        bitcoin-server-main:
                build:
                        context: ./bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server-main
                networks:
                        bitcoin_local_net_main:
                                ipv4_address: 192.168.1.2
                volumes:
                        - /mnt/ssd/bitcoin:/bitcoin
                command: ["bitcoind"]
                
        bitcoin-server-test:
                build:
                        context: ./bitcoin-server
                image: frt/bitcoin-server
                container_name: bitcoin-server-test
                networks:
                        bitcoin_local_net_test:
                                ipv4_address: 192.168.2.2
                volumes:
                        - /mnt/ssd/bitcoin-test:/bitcoin
                command: ["bitcoind", "-testnet"]
                
        bitcoin-access-main:
                build:
                        context: ./bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access-main
                depends_on:
                        - bitcoin-server
                environment:
                        - RPC_HOST=192.168.1.2
                        - RPC_PORT=8332
                networks:
                        bitcoin_local_net_main:
                                ipv4_address: 192.168.1.3
                volumes:
                        - ./bitcoin-access/src:/mnt
                        - /mnt/ssd/bitcoin-dbs:/db
                        - ./out:/out
                        
        bitcoin-access-test:
                build:
                        context: ./bitcoin-access
                image: frt/bitcoin-access
                tty: true
                container_name: bitcoin-access-test
                depends_on:
                        - bitcoin-server-test
                environment:
                        - RPC_HOST=192.168.2.2
                        - RPC_PORT=18332
                networks:
                        bitcoin_local_net_test:
                                ipv4_address: 192.168.2.3
                volumes:
                        - ./bitcoin-access/src:/mnt
                        - /mnt/ssd/bitcoin-dbs:/db
                        - ./out:/out
        
        analytics:
                build:
                        context: ./analytics
                image: frt/blockchain-analytics
                tty: true
                container_name: blockchain_analytics
                environment:
                        - RPC_MAIN_HOST=192.168.1.2
                        - RPC_MAIN_PORT=8332
                        - RPC_TEST_HOST=192.168.2.2
                        - RPC_TEST_PORT=18332
                networks:
                        bitcoin_local_net_main:
                                ipv4_address: 192.168.1.4
                        bitcoin_local_net_test:
                                ipv4_address: 192.168.2.4

networks:
        bitcoin_local_net_main:
                ipam:
                        config:
                                - subnet: 192.168.1.0/24
        bitcoin_local_net_test:
                ipam:
                        config:
                                - subnet: 192.168.2.0/24
